services:
  sparkmaster:
    container_name: sparkmaster
    build: .
    image: spark-image
    entrypoint: ["./entrypoint.sh", "master"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - "9090:8080"
      - "7077:7077"

  sparkhistoryserver:
    container_name: sparkhistory
    image: spark-image
    entrypoint: ["./entrypoint.sh", "history"]
    depends_on:
      - sparkmaster
    env_file:
      - .env.spark
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data
      - spark-logs:/opt/spark/spark-events
    ports:
      - "18080:18080"

  sparkworker:
    container_name: sparkworker
    image: spark-image
    entrypoint: ["./entrypoint.sh", "worker"]
    depends_on:
      - sparkmaster
    env_file:
      - .env.spark
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data
      - spark-logs:/opt/spark/spark-events

volumes:
  spark-logs:
