services:
  keycloak_db:
    image: docker.io/postgres:latest
    container_name: keycloak_db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloakpassword
      - TZ=America/Lima
      - PUID=1000
      - PGID=1000
    ports:
      - 5432:5432
    restart: always
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      #      - KC_BOOTSTRAP_ADMIN_USER=admin
      #- KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DBPASSWORD=keycloakpassword
    command: start-dev
    ports:
      - 8180:8080
    depends_on:
      - keycloak_db
