version: "3.3"

services:
  db:
    image: docker.io/postgres:13
    container_name: postgres
    environment:
      - TZ=America/Lima
      - PUID=1000
      - PGID=1000
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  odoo:
    image: docker.io/odoo:15
    container_name: odoo
    environment:
      - TZ=America/Lima
      - PUID=1000
      - GUID=1000
    ports:
      - 8069:8069
    depends_on: 
      - db
