services:
  postgres:
    image: docker.io/postgres
    container_name: postgres_latest
    environment:
      - TZ=America/Lima
      - PUID=1000
      - PGID=1000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
